import Foundation
import Testing
@testable import KlarityCore

/// Loads a golden fixture generated by scripts/gen-golden.ts from the TS engine.
func golden<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Golden"))
    return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
}

func goldenData(_ name: String) throws -> Data {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Golden"))
    return try Data(contentsOf: url)
}

/// JSON value wrapper so golden fixtures can be decoded as opaque trees and diffed.
enum JSON: Codable, Equatable {
    case null, bool(Bool), number(Double), string(String), array([JSON]), object([String: JSON])

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let b = try? c.decode(Bool.self) { self = .bool(b) }
        else if let n = try? c.decode(Double.self) { self = .number(n) }
        else if let s = try? c.decode(String.self) { self = .string(s) }
        else if let a = try? c.decode([JSON].self) { self = .array(a) }
        else { self = .object(try c.decode([String: JSON].self)) }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .null: try c.encodeNil()
        case .bool(let b): try c.encode(b)
        case .number(let n): try c.encode(n)
        case .string(let s): try c.encode(s)
        case .array(let a): try c.encode(a)
        case .object(let o): try c.encode(o)
        }
    }

    init<E: Encodable>(encoding value: E) throws {
        self = try JSONDecoder().decode(JSON.self, from: JSONEncoder().encode(value))
    }

    /// First differing path, or nil if equal. Numbers compare with a tiny relative tolerance
    /// (JS and Swift print/parse doubles identically, so this only absorbs libm last-bit noise).
    func diff(_ other: JSON, path: String = "$") -> String? {
        switch (self, other) {
        case (.null, .null): return nil
        case (.bool(let a), .bool(let b)): return a == b ? nil : "\(path): \(a) != \(b)"
        case (.string(let a), .string(let b)): return a == b ? nil : "\(path): \"\(a)\" != \"\(b)\""
        case (.number(let a), .number(let b)):
            return abs(a - b) <= 1e-9 * max(1, abs(a), abs(b)) ? nil : "\(path): \(a) != \(b)"
        case (.array(let a), .array(let b)):
            if a.count != b.count { return "\(path): array count \(a.count) != \(b.count)" }
            for (i, (x, y)) in zip(a, b).enumerated() { if let d = x.diff(y, path: "\(path)[\(i)]") { return d } }
            return nil
        case (.object(let a), .object(let b)):
            for k in Set(a.keys).union(b.keys).sorted() {
                switch (a[k], b[k]) {
                case (nil, nil): continue
                case (let x?, nil): if x != .null { return "\(path).\(k): unexpected \(x)" }
                case (nil, let y?): if y != .null { return "\(path).\(k): missing (expected \(y))" }
                case (let x?, let y?): if let d = x.diff(y, path: "\(path).\(k)") { return d }
                }
            }
            return nil
        default: return "\(path): type mismatch \(self) vs \(other)"
        }
    }
}
